language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - cd udagram-api-feed
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed dai175/udagram-api-feed:latest
  - cd ../udagram-api-user
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user dai175/udagram-api-user:latest
  - cd ../udagram-frontend
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend dai175/udagram-frontend:latest
  - cd ../udagram-reverse-proxy
  - docker build -t udagram-reverseproxy .
  - docker tag udagram-reverseproxy dai175/udagram-reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dai175/udagram-api-feed
  - docker push dai175/udagram-api-user
  - docker push dai175/udagram-frontend
  - docker push dai175/udagram-reverseproxy